# Generated by Django 5.0 on 2024-03-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="type",
            field=models.CharField(default="pool", max_length=20),
            preserve_default=False,
        ),
    ]
