# Generated by Django 5.0 on 2024-03-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_dex_network_token_pool_dex_pool_network_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dex",
            name="name",
        ),
        migrations.RemoveField(
            model_name="network",
            name="name",
        ),
        migrations.RemoveField(
            model_name="token",
            name="name",
        ),
        migrations.AddField(
            model_name="dex",
            name="attributes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dex",
            name="external_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="dex",
            name="relationships",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dex",
            name="type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="attributes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="external_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="relationships",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="attributes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="external_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="relationships",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="token",
            name="type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="attributes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="external_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="relationships",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pool",
            name="type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
