# Generated by Django 5.0 on 2024-03-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_dex_name_remove_network_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dex",
            options={
                "ordering": ["id"],
                "verbose_name": "Dex",
                "verbose_name_plural": "Dexes",
            },
        ),
    ]
